on: push

name: 'release'

jobs:
  upload-to-steam:
    name: Upload to Steam Workshop
    runs-on: windows-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - uses: arma-actions/hemtt@v1
      name: Setup HEMTT
    - name: Build
      run: hemtt release
