on: push

name: 'release'

jobs:
  upload-to-steam:
    name: Upload to Steam Workshop
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - uses: arma-actions/hemtt@v1
      name: Setup HEMTT
    - name: Build
      run: hemtt release --no-archive
    #- name: Archive code coverage results
    #    uses: actions/upload-artifact@v4
    #    with:
    #      name: artifact
    #      path: releases/inventory.latest.zip

  #upload-to-steam:
  #  runs-on: ubuntu-latest
  #  name: Upload to Steam Workshop
  #  steps:
    - uses: m00nl1ght-dev/steam-workshop-deploy@v2
      with:
        username: ${{ secrets.STEAM_USERNAME }}
        configVdf: ${{ secrets.STEAM_CONFIG_VDF }}
        path: .hemttout/release
        appId: 107410
        publishedFileId: ${{ secrets.STEAM_PUBLISHED_FILE_ID }}
